### ISSUE TITLE
uninitialized constant Geokit Rails 5

### ISSUE THREAD

**Issue by binodmainali1** [geokit/geokit#204] opened 2017-06-27 07:09 UTC
I am trying to use Geokit gem in rails 5 api only project.
added `gem 'geokit'` in Gemfile

bundle show geokit return me this `/Users/username/.rvm/gems/ruby-2.4.0@rails5/gems/geokit-1.11.0`
But in rails console I get this error
2.4.0 :002 > Geokit
NameError: uninitialized constant Geokit
	from (irb):2
2.4.0 :003 >
Am I missing something here, its working fine in rails 3.2.13 with same configuration but not in rails 5

**Comment by lluis-sancho** [comment] 2017-07-29 10:03
Have you "closed" the console -> exit and restarted again, once you have done the bundle?

**Comment by mokolabs** [comment] 2017-12-02 19:33
FYI... I'm also running into this issue.

**Comment by mokolabs** [comment] 2017-12-02 19:35
Actually, nevermind. It was something else.

**Comment by olleolleolle** [comment] 2021-06-15 06:48
**Unable to reproduce** with Rails 5.2 from the rails/rails 5-2-stable branch.

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rails", github: "rails/rails", ref: "5-2-stable"
```

With this Gemfile present, I could `bundle exec rails new repro` and cd into that directory.

```
bundle add geokit
```

to add and install geokit.

Now, it can be used immediately from the console:

```
➜  repro git:(master) ✗ bundle exec rails c
Running via Spring preloader in process 29785
Loading development environment (Rails 5.2.6)
DEV 08:46:00 >> Geokit
=> Geokit
```

**Comment by ryankopf** [comment] 2023-01-24 04:53
Closing issue as it's been so long and there have been many changes in the code since this comment. If you see this as still being an issue, or experience any other bugs, please open a new issue or submit a PR. Thank you.

**Closed by ryankopf** 2023-01-24 04:53 UTC
